repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: add-gitkeep
        name: Add .gitkeep to empty folders
        entry: bash shell/gitkeep.sh
        language: system
        pass_filenames: false
        types: [python]
